# Generated by Django 4.2 on 2023-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
